using Microsoft.IO;
using Serilog;
using System.Diagnostics;
using System.Text;

namespace SentinelApp.API.Middleware
{
	public class RequestResponseLoggingMiddleware
	{
		private readonly RequestDelegate _next;
		private readonly RecyclableMemoryStreamManager _streamManager;

		public RequestResponseLoggingMiddleware(RequestDelegate next)
		{
			_next = next;
			_streamManager = new RecyclableMemoryStreamManager();
		}
		public async Task InvokeAsync(HttpContext context)
		{
			var stopwatch = Stopwatch.StartNew();

			// Ignore swagger/static files
			if (!context.Request.Path.StartsWithSegments("/api"))
			{
				await _next(context);
				return;
			}

			var logData = new RequestResponseLogData
			{
				Application = "SentinelApp.API",
				Machine = Environment.MachineName,
				User = context.User?.Identity?.Name ?? string.Empty
			};

			await LogRequest(context, logData);

			var originalResponseBody = context.Response.Body;

			await using var responseStream = _streamManager.GetStream();

			context.Response.Body = responseStream;

			try
			{
				await _next(context);

				stopwatch.Stop();

				await LogResponse(
					context,
					responseStream,
					logData,
					stopwatch.ElapsedMilliseconds);

				Log.Verbose(logData.ToString());
			}
			finally
			{
				context.Response.Body = originalResponseBody;

				responseStream.Position = 0;

				await responseStream.CopyToAsync(originalResponseBody);
			}
		}

		private async Task LogRequest(HttpContext context, RequestResponseLogData log)
		{
			context.Request.EnableBuffering();

			log.RequestTimestamp = DateTime.Now;

			log.RequestUri =
				$"{context.Request.Scheme}://{context.Request.Host}{context.Request.Path}{context.Request.QueryString}";

			log.RequestMethod =
				context.Request.Method;

			log.IpAddress =
				$"{context.Request.Host.Host}-{context.Connection.RemoteIpAddress}";

			log.RequestHeaders =
				string.Join(
					Environment.NewLine,
					context.Request.Headers
					.Select(x => $"{x.Key}={x.Value}")
				);

			using var reader =
				new StreamReader(
					context.Request.Body,
					Encoding.UTF8,
					leaveOpen: true);

			log.RequestBody =
				await reader.ReadToEndAsync();

			context.Request.Body.Position = 0;

			// If RequestDecryptMiddleware decrypted it, use the readable version
			var readableRequest = context.Items["ReadableRequest"]?.ToString();
			if (!string.IsNullOrWhiteSpace(readableRequest))
			{
				log.RequestBody = readableRequest;
				log.ReadableRequestBody = readableRequest;
			}
			else if (!string.IsNullOrWhiteSpace(log.RequestBody))
			{
				log.ReadableRequestBody = log.RequestBody;
			}
		}

		private async Task LogResponse(HttpContext context, Stream responseStream, RequestResponseLogData log, long elapsed)
		{

			responseStream.Position = 0;

			log.ResponseBody =
				await new StreamReader(responseStream)
				.ReadToEndAsync();

			log.ResponseStatusCode =
				context.Response.StatusCode;

			log.ResponseTimestamp =
				DateTime.Now;

			log.ElapsedMilliseconds = elapsed;

			// ResponseEncryptMiddleware already encrypts response.
			// If response is encrypted, decrypt for readable logging.

			if (!string.IsNullOrWhiteSpace(log.ResponseBody))
			{
				//log.ReadableResponseBody = "Encrypted response generated by ResponseEncryptMiddleware.";
				log.ReadableResponseBody =context.Items["ReadableResponse"]?.ToString()?? log.ResponseBody;
			}
		}

	}

	public class RequestResponseLogData
	{
		public string Application { get; set; }
		public string Machine { get; set; }
		public string User { get; set; }
		public DateTime? RequestTimestamp { get; set; }
		public string RequestUri { get; set; }
		public string RequestMethod { get; set; }
		public string RequestHeaders { get; set; }
		public string RequestBody { get; set; }
		public string ReadableRequestBody { get; set; }
		public DateTime? ResponseTimestamp { get; set; }
		public long ElapsedMilliseconds { get; set; }
		public int ResponseStatusCode { get; set; }
		public string ResponseBody { get; set; }
		public string ReadableResponseBody { get; set; }
		public string IpAddress { get; set; }

		public override string ToString()
		{
			var separator = new string('-', 50);

			return $@"
{separator}
[REQUEST] {RequestMethod} {RequestUri}
  User:       {User}
  Machine:    {Machine}
  Timestamp:  {RequestTimestamp:yyyy-MM-dd HH:mm:ss}

-- Headers --
{RequestHeaders}

-- Body --
{RequestBody}

{(ReadableRequestBody == RequestBody || string.IsNullOrWhiteSpace(ReadableRequestBody) ? "" : $"-- Readable Body --\n{ReadableRequestBody}\n")}
{separator}
[RESPONSE] {ResponseStatusCode} ({ElapsedMilliseconds}ms)
  Timestamp:  {ResponseTimestamp:yyyy-MM-dd HH:mm:ss}

-- Body --
{ResponseBody}

{(ReadableResponseBody == ResponseBody || string.IsNullOrWhiteSpace(ReadableResponseBody) ? "" : $"-- Readable Body --\n{ReadableResponseBody}\n")}
{separator}";
		}
	}
}
